import { Tokens } from "../tokens";

type ThemeColors = Tokens["colors"]["base"] & {
  filterTextPrimary: string;
  filterTextSecondary: string;
  filterOrangeSecondary: string;
  brandPrimary: string;
  brandSecondary: string;
  brandTertiary: string;
  brandBackground: string;
  gray50: string;
  gray100: string;
  gray200: string;
  gray300: string;
  gray400: string;
  gray500: string;
  gray600: string;
  gray700: string;
  gray800: string;
  gray900: string;
  opacityWhite50: string;
  opacityWhite100: string;
  opacityWhite200: string;
  opacityWhite300: string;
  opacityWhite400: string;
  opacityWhite500: string;
  opacityWhite600: string;
  opacityWhite700: string;
  opacityWhite800: string;
  opacityWhite900: string;
  opacityBlack50: string;
  opacityBlack100: string;
  opacityBlack200: string;
  opacityBlack300: string;
  opacityBlack400: string;
  opacityBlack500: string;
  opacityBlack600: string;
  opacityBlack700: string;
  opacityBlack800: string;
  opacityBlack900: string;
  borderPrimary: string;
  borderSecondary: string;
  borderTertiary: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textPlaceholder: string;
  textDisabled: string;
  textWhite: string;
  textHoverWhite: string;
  backgroundBase: string;
  backgroundElevatedPrimary: string;
  backgroundElevatedSecondary: string;
  backgroundSurfaceBaseDefault: string;
  backgroundSurfaceBasePressed: string;
  backgroundSurfaceBaseDisabled: string;
  backgroundSurfaceElevatedPrimaryDefault: string;
  backgroundSurfaceElevatedPrimaryPressed: string;
  backgroundSurfaceElevatedPrimaryDisabled: string;
  backgroundSurfaceElevatedSecondaryDefault: string;
  backgroundSurfaceElevatedSecondaryPressed: string;
  backgroundSurfaceElevatedSecondaryDisabled: string;
};

type ThemeMode = {
  colors: Tokens["colors"]["light"];
};

export type Theme = {
  borderStyles: Tokens["borderStyles"];
  borderWidths: Tokens["borderWidths"];
  colors: ThemeColors;
  mode: ThemeMode;
  radii: Tokens["radii"];
  shadows: Tokens["shadows"];
  space: Tokens["space"];
};
