export { default as Table } from "./Table";
export { default as TableCaption } from "./TableCaption";
export { default as TableContainer } from "./TableContainer";
export { default as Tbody } from "./Tbody";
export { default as Thead } from "./Thead";
export { default as Tfoot } from "./Tfoot";
export { default as Td } from "./Td";
export { default as Th } from "./Th";
export { default as Tr } from "./Tr";
